### ISSUE TITLE
Mamba ETL Technical Roadmap

### ISSUE THREAD

**Issue by kajambiya** [UCSF-IGHS/ohri-mamba-core#34]
### Feature Work
  - [ ] Move MambaETL DB flattening Task scheduler to base module.
  - [ ] Support for flattening concepts rendered as both questions and answers.
  - [x] A configurable toggle between storing ETL output in the OpenMRS database or in External database.
  - [ ] Ensure that reports data is available while ETL is running.
  - [ ] Incremental update of ETL based on underlying data changes.
  - [ ] Automate addition of Make Scripts in MambaETL.
  - [ ] Service/API layer data pagination support in MambaETL.
  - [ ] Automate column naming in the ETL flattened Tables.
  - [ ] ObsGroups support for MambaETL.
  - [ ] Publish Version 2.0 of MambaETL.
  - [ ] Develop Mamba Report for Total number of Pregnant women attending first ANC.
  - [ ] Develop Mamba Report for Total number of Deliveries.
  - [ ] Develop Mamba Report for Total number of HIV exposed children enrolled in followup care.

### Bugs
  - [ ] Fix build failure when reports.json configuration file is missing.
  - [x] Concepts with multi-select values (e.g. key population) failing to flatten.

### House Keeping
  - [ ] Test report on MambaETL running on MySQL 8.
  - [ ] MambaETL documentation - v1.0.0.
  - [ ] Performance improvement during the flattening process.
  - [ ] Robust Error Handling in MambaETL.
  - [ ] Code cleanups and Refactors in MambaETL.

**Comment by GOmare** [comment]
### Bugs
  - [] Multi-select questions should include their answers as a list of comma separated values under one column (this is not working though there is an SP related (as if) to this.

**Comment by SubhodipPatra** [comment]
Hi @kajambiya , I’m Subhodip Patra from India, currently pursuing my Master’s in CSE at HBTU Kanpur. I’m interested in contributing to the Mamba ETL Technical Roadmap, particularly around incremental ETL updates, performance improvements, pagination in APIs, and bug fixes related to multi-select flattening. I’d be happy to take up a task and submit a PR with guidance. Thanks!

**Comment by kajambiya** [comment]
> Hi [@kajambiya](https://github.com/kajambiya) , I’m Subhodip Patra from India, currently pursuing my Master’s in CSE at HBTU Kanpur. I’m interested in contributing to the Mamba ETL Technical Roadmap, particularly around incremental ETL updates, performance improvements, pagination in APIs, and bug fixes related to multi-select flattening. I’d be happy to take up a task and submit a PR with guidance. Thanks!

Hi @SubhodipPatra This issue list is old but you can talk to @smallgod to guide you on the current issues that you can work on.

**Comment by RounakMishra06** [comment]
Hi @kajambiya and @smallgod,

I’m Rounak Mishra from India and currently exploring OpenMRS repositories as part of my preparation for GSoC 2026.

I came across the Mamba ETL roadmap and found the ETL improvements and performance-related tasks very interesting. I would love to contribute to this module.

Could you please guide me to any current beginner-friendly issues or tasks where I can start contributing?

Thank you!
